# 一 、Numpy

## 1.1 Numpy属性

### 1.1.1 属性
	
* `ndim` : 维度
	
* `shape`: 行数和列数
	
* `size` : 元素个数
	
* `dtype` :  元素类型

### 1.1. 2 属性使用方法

In [3]:
# 首先导入模块
import numpy as np # 为了方便使用numpy模块，起别名为np。

# 
array = np.array([[1, 2, 3], [2, 3, 4]])
array

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
# 维度
array.ndim 

2

In [5]:
# 行数和列数
array.shape

(2, 3)

In [6]:
# 元素个数
array.size

6

In [8]:
# 元素类型
array.dtype

dtype('int64')

In [10]:
# array的类型
type(array)

numpy.ndarray

## 1.2 数组Array

### 1.2.1 创建数组的方法

* `array` : 列表创建数组
* `zeros` : 创建元素为零的数组
* `ones` : 创建元素全为1的数组
* `empty` : 创建元素接近零的数组。
* `arange` : 指定范围创建数组
* `linspace` : 创建连续数据段数组

### 1.2.2 示例

In [11]:
# array 
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
# 元素类型
a.dtype

dtype('int64')

In [13]:
# 元素为float
b = np.array([1.1, 1.3, 2.3])
b.dtype

dtype('float64')

In [15]:
# 指定元素类型
c = np.array([1.1, 3.1, 3.4], dtype=np.float32)
c.dtype

dtype('float32')

In [17]:
# 创建zero数组
a = np.zeros((3, 4))

b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [18]:
# 创建元素为1的数组
b = np.ones((2,3,4), dtype=np.int16)
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
# 空数组
e = np.empty( (2,3) )
e

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
# 用arange创建连续数组
a = np.arange(10, 20, 2) # 10 - 19 的数据，步长为2
a

array([10, 12, 14, 16, 18])

In [24]:
# reshape改变数组的形状
a = np.arange(12).reshape((3,4))
a # 3行4列，0到11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# linspace创建线段型数据
a = np.linspace(1, 10, 20) # 开始1，结束10 分割20个数据。
a

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

## 1.3 基本运算

### 1.3.1 元素运算

基本算数运算作用在数组的每个元素上。`+`,`-`,`*`,`**`等。

In [26]:
# 创建两个数组
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [27]:
# 加法
c = a + b
c

array([20, 31, 42, 53])

In [28]:
# 减法
c = a - b
c

array([20, 29, 38, 47])

In [29]:
# 乘法
c = a * b
c

array([  0,  30,  80, 150])

In [30]:
# 乘方
c = b ** 2
c

array([0, 1, 4, 9])

与数组元素运算不同的，矩阵运算需要使用`dot`函数

In [32]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

# 矩阵
A.dot(B)

# OR
np.dot(A, B) # 矩阵相乘


array([[5, 4],
       [3, 4]])

其他的一些运算，例如 `sum()`,`min()`,`max()`。

In [36]:
a = np.random.random((2, 3))
print(a) # 打印数组
print(a.sum()) # 总和
print(a.min()) # 最小值
print(a.max()) # 最大值

[[ 0.5427813   0.85578629  0.29093845]
 [ 0.46005945  0.04124305  0.578342  ]]
2.76915055148
0.0412430486922
0.855786294036


添加`axis`参数，指定计算的轴。

In [40]:
b = np.arange(12).reshape((3,4))
print(b)
print('---------------')
print(b.sum(axis=0))
print(b.min(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------
[12 15 18 21]
[0 4 8]


### 1.3.2 通用函数

在`Numpy`中提供常见的数学函数。例如`sin`,`cos`和`exp`等。[官方文档](https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations)

In [43]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


## 1.4 索引，切片

### 1.4.1 一维数组


In [51]:
a = np.arange(10) ** 3
print(a)
print('--------------')
print(a[2]) # 下标为2的元素，从0开始
print(a[2:5]) # 下标2，3，4的元素
print(a[:6:2]) # 下标0-6的元素，步长2

[  0   1   8  27  64 125 216 343 512 729]
--------------
8
[ 8 27 64]
[ 0  8 64]


### 1.4.2 多维数组
在多维数组中，每个轴都可以有一个索引。

In [54]:
b = np.arange(20).reshape((5,4))
print(b)
print('---------------')
print(b[2,3]) # 下标为2的行下标为3的列的元素。
print(b[0:5, 1]) # 行号0-5，列号1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
---------------
11
[ 1  5  9 13 17]


## 1.5 数组合并

In [58]:
# 创建数组
a = np.array([[1,1],[0,0]])
print(a)
b = np.array([[2,2],[0,0]])
print(b)

[[1 1]
 [0 0]]
[[2 2]
 [0 0]]


In [59]:
# vstack() 垂直方向合并
np.vstack((a,b))

array([[1, 1],
       [0, 0],
       [2, 2],
       [0, 0]])

In [60]:
# hstack() 水平方向合并
np.hstack((a,b))

array([[1, 1, 2, 2],
       [0, 0, 0, 0]])

## 1.6 数组分割

In [70]:
a = np.array(10*np.random.random((2,12)), dtype=np.int64)
a

array([[7, 5, 1, 5, 6, 1, 3, 2, 9, 4, 3, 9],
       [5, 7, 4, 7, 3, 9, 2, 9, 8, 7, 9, 5]])

In [71]:
# 水平分割
np.hsplit(a, 3) # 分割成三个数组

[array([[7, 5, 1, 5],
        [5, 7, 4, 7]]), array([[6, 1, 3, 2],
        [3, 9, 2, 9]]), array([[9, 4, 3, 9],
        [8, 7, 9, 5]])]

In [72]:
# 垂直分割
np.vsplit(a, 1)

[array([[7, 5, 1, 5, 6, 1, 3, 2, 9, 4, 3, 9],
        [5, 7, 4, 7, 3, 9, 2, 9, 8, 7, 9, 5]])]

## 1.7 深浅拷贝

In [63]:
# 创建数组
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 1.7.1 浅拷贝

In [65]:
# 浅拷贝
c = a.view()
print(c is a) # False
print(c.base is a) # True

True

### 1.7.2 深拷贝

In [67]:
# 深拷贝
d = a.copy()
print(d is a)
print(d.base is a)

False
False
